name: flow_matching
channels:
  - pytorch
  - conda-forge
  - nvidia
dependencies:
  - python=3.9
  - pytorch
  - pytorch-cuda
  - matplotlib
  - jupyter
  - numpy
  - pip
  - tqdm
  - pip:
    - pre-commit
     
